### ISSUE TITLE
How to set connection timeout

### ISSUE THREAD

**Issue by Ndhb478** [graze/telnet-client#13]
Hi!

I have a question about setting a connection timeout. I played a litte with your documented "$client->getSocket()->setOption()" but I think this way only works if the socket was created successfully?

Greetings,
Sebastian

**Comment by john-n-smith** [comment]
Hi Sebastian, 

You are correct, the `getSocket()` method will only return a valid `Socket` after a successful call to `connect()`.

An alternative would be to create the `Socket` object yourself, specifying the timeout, then pass it into TelnetClient, e.g.:

```
$socketFactory = new \Socket\Raw\Factory();
$timeoutSeconds = 2.5;
$socket = $factory->createClient('www.google.com:80', $timeoutSeconds);

$telnet = new Graze\TelnetClient\TelnetClient();
$telnet->setSocket($socket);
```

This a workaround for the fact that `TelnetClient ::connect()` does not currently have a `$timeout` argument.

**Comment by brendankay** [comment]
Hi Sebastian,

I've just added a `$timeout` param to `TelnetClient::connect()`:
https://github.com/graze/telnet-client/pull/14/commits/85b5d5b9e218006d8a8e32cac61a8d832ff34cba#diff-75c6bba818fce5de93127dcf7f3f8c33R111

You can get this change by updating to v2.1.0

Cheers,
Brendan
