### ISSUE TITLE
Can't get login to work on MS Telnet

### ISSUE THREAD

**Issue by styper** [graze/telnet-client#15]
I can't seem to get this to work with MS Telnet Server. The program just hangs

This is an output of a successful connection:

> Trying 192.168.50.59...
> Connected to 192.168.50.59.
> Escape character is '^]'.
> Welcome to Microsoft Telnet Service 
> 
> login: erick 
> password: 
> 
> *===============================================================
> Microsoft Telnet Server.
> *===============================================================

This is the code I'm using:

```
$host = '192.168.50.59';
$port = 23;
$telnet = TelnetClient::factory();
$telnet->connect("$host:$port");
var_dump($telnet->execute('erick', 'password:'));
```

This is what I get when I var_dump the buffer:

> string(47) "Welcome to Microsoft Telnet Service
> 
> login: "

So the connection seems to be working as the buffer is loading but then it just hangs when I try to log in

**Comment by john-n-smith** [comment]
You need to let the client know what response to expect. By default it's waiting for the string `$\n`, however, from your dump I can see that the last output from the server is `login: `.

You need to configure the client to expect this, e.g.
```

**Comment by john-n-smith** [comment]
I'm afraid you're working against some design decisions that were based on telnet implementations from embedded devices. Other implementations (such as this one) seem to work a little differently. 

I've released [this small change](https://github.com/graze/telnet-client/releases/tag/v2.2.0) that should allow you to work around them. Could you try the following (some tweaks may be necessary):

```
$dsn = '192.168.50.59:23';
$client = Graze\TelnetClient\TelnetClient::factory();

// server does not respond with consistent line ending - set this to null
$client->setLineEnding(null);
$client->connect($dsn);

// send something ("\r\n") to the server to trigger its initial response. Look for "login: " in the response
$resp = $client->execute("\r\n", "login: ");

// send username with line ending appended as it is no longer included. Look for "password: " prompt
$resp = $client->execute("erick\r\n", "password: ");

// send password with line ending. Look for welcome banner
$welcomePrompt = "*======="; //... full string or regex
$resp = $client->execute("my password\r\n", $welcomePrompt);
...
```

As `$lineEnding` is now `null`, it will have to be appended to each of your commands (if that's what the server is looking for to denote a send)

Let me know if it works.

**Comment by styper** [comment]
Thanks for the response, I tried messing around with setting the line endings but no luck

This is the code tested now:

```
$dsn = '192.168.50.59:23';
$client = TelnetClient::factory();
$client->setLineEnding(null);
$client->connect($dsn);
$resp = $client->execute("\r\n", "login: ");
var_dump($resp); //This line is never reached as the program hangs in the line before
```

The buffer var_dump is as before:

> string(45) "Welcome to Microsoft Telnet Service
> 
> login"
> string(46) "Welcome to Microsoft Telnet Service
> 
> login:"
> string(47) "Welcome to Microsoft Telnet Service
> 
> login: "

Which is strange because replicating the results in a telnet shell works as you expected, the login line is printed again:

> Trying 192.168.50.59...
> Connected to 192.168.50.59.
> Escape character is '^]'.
> Welcome to Microsoft Telnet Service 
> 
> login: 
> login: 

I tried using \r, \n and \r\n and got the same results

**Comment by styper** [comment]
Thanks for the quick response. I had posted a comment before but deleted it since I forgot to update before the test.

Your change worked like a charm, this is the code used and the results:

```
$dsn = '192.168.50.59:23';
$client = TelnetClient::factory();
$client->setLineEnding(null);
$client->connect($dsn);
$resp = $client->execute("\r\n", "login: ");
var_dump($resp);
$resp = $client->execute("erick\r\n", "password: ");
var_dump($resp);
$welcomePrompt = "erick>";
$resp = $client->execute("erick\r\n", $welcomePrompt);
var_dump($resp);
```

> object(Graze\TelnetClient\TelnetResponse)#134 (3) {
>   ["isError":protected]=>
>   bool(false)
>   ["responseText":protected]=>
>   string(40) "Welcome to Microsoft Telnet Service
> 
> 
> "
>   ["promptMatches":protected]=>
>   array(1) {
>     [0]=>
>     string(7) "login: "
>   }
> }
> object(Graze\TelnetClient\TelnetResponse)#142 (3) {
>   ["isError":protected]=>
>   bool(false)
>   ["responseText":protected]=>
>   string(21) "erick
> login: erick
> "
>   ["promptMatches":protected]=>
>   array(1) {
>     [0]=>
>     string(10) "password: "
>   }
> }
> object(Graze\TelnetClient\TelnetResponse)#134 (3) {
>   ["isError":protected]=>
>   bool(false)
>   ["responseText":protected]=>
>   string(171) "
> 
> *===============================================================
> Microsoft Telnet Server.
> *===============================================================
> C:\Users\"
>   ["promptMatches":protected]=>
>   array(1) {
>     [0]=>
>     string(6) "erick>"
>   }
> }

Thank you very much!

**Comment by styper** [comment]
For reference this is a Windows 7 Professional machine using standard MS Telnet Server

**Comment by john-n-smith** [comment]
Glad you got it working 👍
