### ISSUE TITLE
End sequence not found causing infinite loop in getResponse()

### ISSUE THREAD

**Issue by kinekt4** [graze/telnet-client#17]
Running the following on the command line:

    LOGIN:::01::UN=user01,PWD=pass01;

Results in a response similar to this:

    \r\n
    \n
       0 2018-11-11 11:11:11\r\n
    M  01 COMPLD\r\n
       EN=0   ENDESC=Succeeded.\r\n
    ;

Running the following just hangs:

    $client = Graze\TelnetClient\TelnetClient::factory();
    $dsn = '127.0.0.1:23';
    $client->connect($dsn);
    $command = 'LOGIN:::01::UN=user01,PWD=pass01;';
    $resp = $client->execute($command, ';');
    var_dump($resp);

I get the full response when I dump out the buffer, but the script just hangs and does not print a response.

**Environment**
- I believe the Telnet server is a windows machine

**Background**
- I'm sending TL1 commands (Telecom)

**Comment by kinekt4** [comment]
Actually, it's stuck in an infinite loop in getResponse(), at least for my use case

**Comment by john-n-smith** [comment]
It sounds like the `execute` call is not finding the end sequence specified.

The end sequence is made up of `$prompt . $lineEnding`. By default, `$lineEnding` is `\n` so in your example, the client is looking for `;\n` before it returns.

Setting the line ending to `;` will get you most of the way there, but the client still needs a prompt. As a quick test you can use an empty string:
```
$client = Graze\TelnetClient\TelnetClient::factory();
$client->setLineEnding(';');
$dsn = '127.0.0.1:23';
$client->connect($dsn);
$command = 'LOGIN:::01::UN=user01,PWD=pass01'; // notice line ending removed - it will be appended by the client
$resp = $client->execute($command, '');
var_dump($resp);
```

If the above works, you can define a more complex prompt using a regex to parse out any interesting information.

**Comment by kinekt4** [comment]
Thanks @john-n-smith .

Your suggestion seems to work with one proviso:

The following code in `TelnetClient` needs to change from

    # TelnetClient::getResponse():233
    // check for prompt
    if ($this->promptMatcher->isMatch($prompt ?: $this->prompt, $buffer, $this->lineEnding)) {
        break;
    }

To:

    # TelnetClient::getResponse():233
    // check for prompt
    $prompt = isset($prompt) ? $prompt : $this->prompt;
    if ($this->promptMatcher->isMatch($prompt, $buffer, $this->lineEnding)) {
        break;
    }

The reason is that the empty string forces the ternary operator to set the default `$this->prompt` to the `$prompt` variable. Consequently, the pattern being matched in `PromptMatcher` is `/\$;$/` instead of `/;$/`

**Comment by kinekt4** [comment]
> The reason is that the empty string forces the ternary operator to set the default $this->prompt to the $prompt variable. Consequently, the pattern being matched in PromptMatcher is /\$;$/ instead of /;$/

To overcome this issue, I've added non empty values as `$prompt`

    $resp = $client->execute($command, "\r\n");

btw. I've explicitly added \r\n to the other lines on the original post

**Comment by john-n-smith** [comment]
Glad you managed to get it working. I'm afraid you're working against some assumptions about telnet servers that were made based on embedded implementations, i.e. that all responses are terminated with a consistent prompt and line ending. I'm hoping to spend some time refactoring the client to take these findings into account.
