### ISSUE TITLE
Propose execute() should accept $promptError parameter

### ISSUE THREAD

**Issue by kinekt4** [graze/telnet-client#18]
According to the current design, `execute()` only accepts one parameter: `$prompt`

This assumes that `$promptError` is static, and `$prompt` is dynamic.

Hence, `$promptError` can only be set on initialisation where `$prompt` can be set on every call to `execute()`

I propose that `$promptError` should be treated the same as `$prompt`, in that it can be set dynamically.

Effectively, I'm proposing `execute()` should accept another parameter `$promptError`

    public function execute($command, $prompt = null, $promptError = null)
    {
        ...
        return $this->getResponse($prompt, $promptError);
        ...

Consequently, `getResponse()` will also have to accept one more parameter

    protected function getResponse($prompt = null, $promptError = null)
    {
        ...
        $promptError = isset($promptError) ? $promptError : $this->promptError;
        if ($this->promptMatcher->isMatch($promptError, $buffer, $this->lineEnding)) {
        ...

What are your thoughts?

**Comment by john-n-smith** [comment]
Thanks for the proposal and solid reasoning - that all makes sense and would be a non-breaking change. If you want to create a PR, I'd be happy to merge it into the main branch and release as v2.3.0.

That being said, as hinted at in #17, I'm planning on refactoring the main API and releasing as v3.0.0. This would be taking on board what I've learnt from other implementations via Issues (such as your own) and hopefully simplifying things.

I'll create a new issue with a proposal if you'd care to take a look?

**Comment by kinekt4** [comment]
Yes, please go ahead.

This is my first source contribution, so I'm just feeling my way around a bit.

**Comment by john-n-smith** [comment]
If you create a fork of this project and make your changes, you can then create a Pull Request from GitHub. This will allow me to review the code and merge it into the master branch.

It may not be worth doing the work however as I've almost finished v3.0.0 which should be flexible to work for your use case.
