### ISSUE TITLE
How to check for prompt and include it in response text

### ISSUE THREAD

**Issue by roarkmccolgan** [graze/telnet-client#19]
Thanks for the great package,

My response is XML and I'm able to get the response (and avoid the endless loop #17 ) by using the below command

```
$response = $client->execute($command,preg_quote('</response>','/'));
```

I'm waiting for `</response>`

However `getResponseText()` returns everything but the `</response>` invalidating the xml.

How do I keep the end sequence in the response please?

Thank you!

**Comment by john-n-smith** [comment]
Hi, sorry for the slow reply.

The current implementation assumes the `$prompt` is not an important part of the response and chops it off.

As a workaround, you could make your `$prompt` pattern match the whole response then use `$response->getPromptMatches()`. 

Assuming your response looks something like
```
<response><something attrib="something"><nested></nested></response>
```

Your prompt could be something like `^<response>.*<\/response>$`.

[Version 3](https://github.com/graze/telnet-client/tree/version-3) is underway and would match your use case better, but it's still a little way off.

**Comment by roarkmccolgan** [comment]
Hey John

Thanks for getting back to me, I was simply concatenating `</response>` on the end of the response text 😜 your solution seems more elegant for now until Version 3! Looking forward to it,

Thank you!
