### ISSUE TITLE
The execute method doesn't work

### ISSUE THREAD

**Issue by aziev** [graze/telnet-client#21]
I'm trying to connect Memcached server on localhost:11211 and run the `get` command.

```
$prompt = 'OK';
$promptError = 'ERROR';
$lineEnding = "\r\n";
$this->telnet->connect("localhost:11211", $prompt, $promptError, $lineEnding);
$resp = $this->telnet->execute("get some_key");
var_dump($resp->getResponseText());
```

I run this code via phpunit from PowerShell but it doesnt do anything. No error shown but also no any other output. And the console looks like it still executing.

![image](https://user-images.githubusercontent.com/11891491/61174049-c5e6cb80-a5a3-11e9-87a5-e9cf2ec7de2b.png)

The same result if I try run any other Memcached command. However these commands works fine from Powershell telnet and from Putty.

Any thoughts?

**Comment by biggianteye** [comment]
Hi there. Are you sure that your memcached instance is prompting with `OK`?

I've just run this slightly modified version of your code:

```php
$telnet = Graze\TelnetClient\TelnetClient::factory();
$prompt = '';
$promptError = 'ERROR';
$lineEnding = "\r\n";
$telnet->connect("localhost:11211", $prompt, $promptError, $lineEnding);
$resp = $telnet->execute("get some_key");
var_dump($resp->getResponseText());
```

And got this result:

```
root@414973d37ab1:/srv# php telnet-test.php
/srv/telnet-test.php:12:
string(3) "END"
```

This matches the behaviour when using a standalone telnet client:

```
root@414973d37ab1:/srv# telnet 127.0.0.1 11211
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
get some_key
END
```
When I ran it with a prompt of `OK` it sat there doing nothing because it was waiting for `OK` to appear.

**Comment by aziev** [comment]
@biggianteye Now I see that I was using it wrong. But at the moment I can't test it. We can just close the issue. Thanks
