### ISSUE TITLE
unable to create socket connection

### ISSUE THREAD

**Issue by ghost** [graze/telnet-client#22]
When attempting to run the initial tests the following fault appears:

"unable to create socket connection to [127.0.0.1:23]"

The development machine has permission released on port 23 for telnet access.
I could not get a resolution of the problem, can you help me?

**Comment by biggianteye** [comment]
I'm not very familiar with this library, but it looks like there are only unit tests which mock the external resources. You shouldn't need to open any ports for telnet access on your machine.

What command were you running and what was the complete output?
