### ISSUE TITLE
Login Password only

### ISSUE THREAD

**Issue by 0stone0** [graze/telnet-client#29]
Based on #9 and #15, I'm trying to login to my VLC Telnet socket with the following code:
```
use Graze\TelnetClient\TelnetClient;

class MyTelNet {

    function __construct

        // Get Client
        $this->c = TelnetClient::factory();

        // Connect
        $this->c->setLineEnding("\r\n");
        $this->c->connect('127.0.0.1:4212');

        // Authenticate
        $resp = $this->c->execute("myfancypasswordi\r\n", "Password: ");
        var_dump($resp);
    }
}
```

From which I receive the following error:
>  Socket\Raw\Exception: Socket operation failed: Connection refused (SOCKET_ECONNREFUSED)

Please suggest any other login attempt, the other issues doen't work. (Using `localhost` instead off `127.0.0.1` gives the same output)

A CLI successful login looks as follows:
```
pi@raspberrypi:~ $ telnet 127.0.0.1 4212
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
VLC media player 3.0.11 Vetinari
Password:
Welcome, Master
>
```

**Comment by biggianteye** [comment]
Hi @0stone0 . I see that you've closed this. Did you solve your problem or do you still need help?
